mariadb:
    build: dockerfiles/mariadb
    env_file: .env
    volumes:
        - "./mariadb:/var/lib/mysql"
    expose:
        - "3306"
    restart: always

php-fpm:
    build: dockerfiles/php-fpm
    env_file: .env
    volumes:
        - "./php-fpm/extra.ini:/etc/php/conf.d/extra.ini"
        - "./nginx/html:/usr/share/nginx/html"
    expose:
        - "9000"
    links:
        - "mariadb:mariadb"
    restart: always

nginx:
    build: dockerfiles/nginx
    env_file: .env
    volumes:
        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        - "./nginx/html:/usr/share/nginx/html"
    ports:
        - "80:80"
    links:
        - "php-fpm:php-fpm"
    restart: always

